# OTLP export
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=10s

otel.exporter.otlp.endpoint=http://localhost:4317
otel.service.name=micrometer-module

# Expose actuator metrics endpoint
management.endpoints.web.exposure.include=health,metrics,prometheus

management.tracing.enabled=true
management.otlp.tracing.endpoint=http://localhost:4317